name: FORMAT
version: 1.4.4
date: 2024-01-09
description: |
    Computing with formations of finite solvable groups.

authors:
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick
    - name: Charles R.B. Wright
      url: https://pages.uoregon.edu/wright/

maintainers:
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.5"

www: https://gap-packages.github.io/format/
readme: README.md
packageinfo: https://gap-packages.github.io/format/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/format/releases/download/v1.4.4/format-1.4.4.tar.gz

abstract: |
    This package provides functions for computing with formations of finite solvable groups.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
