name: FORMAT
version: 1.3
date: 2012-05-26
description: |
    Computing with formations of finite solvable groups.

authors:
    - name: Bettina Eick
      url: http://www.icm.tu-bs.de/~beick
    - name: Charles R.B. Wright
      url: http://www.uoregon.edu/~wright

maintainers:
    - name: Bettina Eick
      url: http://www.icm.tu-bs.de/~beick
    - name: Charles R.B. Wright
      url: http://www.uoregon.edu/~wright

GAP: ">=4.5"

www: http://www.uoregon.edu/~wright/RESEARCH/format/
readme: README
packageinfo: http://www.uoregon.edu/~wright/RESEARCH/format/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://www.uoregon.edu/~wright/RESEARCH/format/format-1.3.tar.gz
    - name: .tar.bz2
      url: http://www.uoregon.edu/~wright/RESEARCH/format/format-1.3.tar.bz2

abstract: |
    This package provides functions for computing with formations of finite solvable groups.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
